AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Outputs: {}
Resources:
  ScheduledJobScrapeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - ssm:GetParameter
            Resource: arn:aws:ssm:*:*:parameter/*
          - Effect: Allow
            Action:
            - kms:Decrypt
            Resource: arn:aws:kms:*:*:key/*
        PolicyName: ScheduledJobScrapeRolePolicy
  ScheduledJobScrape:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: app.scheduled_job_scrape
      CodeUri: s3://semantic-job-search-bucket/26c8082d5fb6899549d5070157531617
      Tags:
        aws-chalice: version=1.30.0:stage=dev:app=semantic-job-match
      Tracing: PassThrough
      Timeout: 300
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - ScheduledJobScrapeRole
        - Arn
      Events:
        ScheduledJobScrapeEvent:
          Type: Schedule
          Properties:
            Schedule: cron(25 3 ? * * *)
