AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Outputs: {}
Resources:
  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:*:logs:*:*:*
        PolicyName: DefaultRolePolicy
  ScheduledJobScrape:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: app.scheduled_job_scrape
      CodeUri: s3://semantic-job-search-bucket/794eb21a5564212e3a39fbecd1a71cf9
      Tags:
        aws-chalice: version=1.30.0:stage=dev:app=swifthire-cloud
      Tracing: PassThrough
      Timeout: 60
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - DefaultRole
        - Arn
      Events:
        ScheduledJobScrapeEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * MON-FRI *)
